<a href="https://colab.research.google.com/github/Tahira2910/Deep-Learning/blob/main/Multiple_Classification_using_IRIS_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}"with length {length} bytes'.format(
      name = fn, length = len(uploaded[fn])))

Saving iris.csv to iris.csv
User uploaded file "iris.csv"with length 4551 bytes


In [2]:
import pandas as pd
import io
data = pd.read_csv(io.StringIO(uploaded['iris.csv'].decode('utf-8')))

In [3]:
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [4]:
import keras
# Sequential--> classification technique based on step by step(In sequence)
from keras.models import Sequential
# Dense--> use for adding layers, input layer, hidden layer...
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

In [5]:
data

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [6]:
# X--> ind, Y--> Dep
X = data.iloc[:, 0:4].values
Y = data.iloc[:, 4].values

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1 = encoder.fit_transform(Y)
y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [11]:
model = Sequential()
model.add(Dense(4, input_shape=(4,), activation='relu'))

# for multiple classsification, we use softmax activation function(final output )

# output quantity: 3(0,1,2)
model.add(Dense(3, activation='softmax'))

In [14]:
# Now, we will compile our classifier
# output prediction is in binary(B or M) so, using binary_crossentropy
# and for multiple, categorical_crossentropy
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [19]:
model.fit(X_train, y_train,batch_size=10, epochs=100)

Epoch 1/100
12/12 [==============================] - 1s 2ms/step - loss: 1.1348 - accuracy: 0.2605
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 1.1080 - accuracy: 0.4874
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0897 - accuracy: 0.6134
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0754 - accuracy: 0.5798
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0617 - accuracy: 0.5798
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0498 - accuracy: 0.5798
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0387 - accuracy: 0.5714
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0284 - accuracy: 0.5630
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0170 - accuracy: 0.5882
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 1.0065 - accuracy: 0.6050
Epoch 11/

In [20]:
y_pred = model.predict(X_test)
# axis=1 for rows
y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

1/1 [==============================] - 0s 75ms/step


In [22]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.71      1.00      0.83        10
           2       1.00      0.50      0.67         8

    accuracy                           0.87        30
   macro avg       0.90      0.83      0.83        30
weighted avg       0.90      0.87      0.86        30

[[12  0  0]
 [ 0 10  0]
 [ 0  4  4]]


In [23]:
(12+10+4)/30

0.8666666666666667