**Introduction To Tensors**

In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [3]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the no of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([[10,10], [11,10]])
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [11, 10]], dtype=int32)>

In [6]:
# Check the dimension of our vector
vector.ndim

2

In [7]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7]])
matrix

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

In [8]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7], [7,10]], dtype = tf.int8)
matrix

<tf.Tensor: shape=(2, 2), dtype=int8, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int8)>

In [10]:
matrix.ndim

2

In [11]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                             [3., 2.],
                             [8., 9.]])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [12]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                             [3., 2.],
                             [8., 9.]], dtype=tf.float16) # Specify the datatype as dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
# What's the no dimensions of another_matrix?
another_matrix.ndim

2

In [14]:
# Let's create a Tensor
# shape=(3, 2, 3)--> 3(total 3 pairs), 2--> two two rows in each pair
# 3--> three three col
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],

                      [[7, 8, 9],
                       [10, 11, 12]],

                     [[13, 14, 15],
                      [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [15]:
tensor.ndim

3

# **Creating tensors with tf.Variables**

In [16]:
#Creating the same tensor eith tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
changeable_tensor[0]=8
changeable_tensor

TypeError: ignored

In [18]:
# How about we try .assign()
changeable_tensor[0].assign(8)


<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [19]:
# Let's try change our unchangable tensor
unchangeable_tensor[0] = 7

TypeError: ignored

In [20]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In [21]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #Set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [22]:

# Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [23]:
# shuffle the data
shuffled = tf.constant([[10,7],[3,2],[2,5]])
tf.random.shuffle(shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  2],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [24]:
# shuffle the data
# using seed inside paranthesis..still list order shuffles
shuffled = tf.constant([[10,7],[3,2],[2,5]])
tf.random.set_seed(42)
tf.random.shuffle(shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 2,  5]], dtype=int32)>

In [25]:
# Create a tensor of all ones
tf.ones([4,7])

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
# Create a tensor of all ones
tf.zeros([4,7])

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Getting information from tensors

When dealing with tensors, you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [27]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
tf.size(rank_4_tensor)
# size--> 120 elements

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [29]:
# Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions(rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Total no of elements in our tensor: ", tf.size(rank_4_tensor).numpy())


Datatype of every element:  <dtype: 'float32'>
Number of dimensions(rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Total no of elements in our tensor:  120


##Indexing tensors

Tensors can be indexed just like Python lists.

In [30]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
# Getting the last item of each of row of our rank 2 tensor
rank_4_tensor[:, -1]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [34]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

## Change datatype:From float32 to float16
 ( reduced precision)

In [35]:
B = tf.constant([4.8, 7.3])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.8, 7.3], dtype=float32)>,
 tf.float32)

In [36]:
# Change from float32 to float16
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([4.8, 7.3], dtype=float16)>,
 tf.float16)

In [37]:
C = tf.constant([5, 6])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>,
 tf.int32)

In [38]:
# Change from float32 to float16
D = tf.cast(C, dtype = tf.int16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([5, 6], dtype=int16)>,
 tf.int16)

**Finding the positional maximum**

In [39]:
#   Returns the index with the largest value across axes of a tensor
tf.argmax(D)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

## One-hot encoding tensors

In [40]:
# Create a linst of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

In [41]:
# depth = 4( 4 elements in some_list)
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [42]:
# Specify custom value for one-hot encoding
tf.one_hot(some_list, depth =4, on_value='Deep Learning', off_value="I am hungry")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Deep Learning', b'I am hungry', b'I am hungry', b'I am hungry'],
       [b'I am hungry', b'Deep Learning', b'I am hungry', b'I am hungry'],
       [b'I am hungry', b'I am hungry', b'Deep Learning', b'I am hungry'],
       [b'I am hungry', b'I am hungry', b'I am hungry', b'Deep Learning']],
      dtype=object)>